### ISSUE TITLE
Homebridge missing <platform>

### ISSUE THREAD

**Issue by Jbakim** [neskvern/homebridge-tibber#2]
What is the correct platform name? 

Sample configuration

????----->      "platform": "homebridge-tibber",     <---- ????
                         "accessory": "tibber-power-consumption",
                         "name": "Tibber Power",
                         "feedUrl": "wss://api.tibber.com/v1-beta/gql/subscriptions",
                         "queryUrl": "https://api.tibber.com/v1-beta/gql",
                         "apiKey": "vmcGfxxxxxxxxfzRA0rp6xxxxxfSJNm0sk",
                         "homeId": "73599911xxxxxxxxx6"

**Comment by neskvern** [comment]
You should put the configuration under "accessories".
