### ISSUE TITLE
Suddenly stops updating

### ISSUE THREAD

**Issue by redjoto** [neskvern/homebridge-tibber#3]
The plugin suddenly stops updating data and I have to restart Homebridge to make it work again. Happened twice since I installed the plugin two days ago. Anyone else experiencing the same?

**Comment by FamJohansson** [comment]
I am having the same problem with my home ridge. I need to restart it twice a day

**Comment by neskvern** [comment]
I know Tibber API had problems with instability lately, but I think it works better now.
