### ISSUE TITLE
0 values

### ISSUE THREAD

**Issue by Stianker1** [neskvern/homebridge-tibber#4]
Hi,
I just installed my tibber pulse and wanted to try this plugin out. I have fetched på token and House id from tibber api, but there is no values in the eve app. In the logs it says "disconnected from tibber feed". 
Is there something im doing wrong?

Best regards,
Stian

**Comment by neskvern** [comment]
Maybe Tibber API endpoint was down at the moment? I have justed tested an updated version and it works ok now.
