### ISSUE TITLE
Breaking changes in Tibber API

### ISSUE THREAD

**Issue by toini** [neskvern/homebridge-tibber#5]
Hi!

I would like to thank you for contributing to the community of Tibber users. You are on the list of people we respect! https://developer.tibber.com/respect

In order to improve the API resilience we are making a breaking change for websocket communication. Please see details at [developer site](https://developer.tibber.com/). Would you be able to adjust the implementation accordingly?

Also, it looks like you might not be setting user-agent header value according to best practices. A recommended format would be to include both the platform version and driver version for example like this: `Homebridge/1.2.3 neskvern-homebridge-tibber/0.0.23`.

We're trying to collect best practices [here](https://developer.tibber.com/docs/guides/calling-api)

Let us know if in need of any assistance!

Br,
Toni
Tibber

**Comment by neskvern** [comment]
Hello, and thank you for this information!

Updated to new version of tibber-api. Should be ok for now.
